name: getting_started_react
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jermaine Oppong <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0
  react: ^4.5.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
